### ISSUE TITLE
Please use http:// link in the repo description

### ISSUE THREAD

**Issue by MarSik** [kubevirt/run#3]
The https://run.kubevirt.io link has certificate issue as it runs on www.github.com domain and the cert does not match the hostname.

**Comment by mykaul** [comment]
Also the main description refers to https://kubevirt.io/

**Comment by fabiand** [comment]
Thanks!

The description of the urn repo has been fixed.

@mykaul which main description are you refering to?

**Comment by mykaul** [comment]
https://github.com/kubevirt

**Comment by fabiand** [comment]
Thanks. This was fixed as well.
