### ISSUE TITLE
Redirection causes wrong exit code in Fedora when looking for installed packages

### ISSUE THREAD

**Issue by dougbtv** [kubevirt/run#4]
Using the docs from the kubevirt/kubevirt repo to curl the script and pipe to bash, I ran into an issue where it wasn't detecting that packages were installed on Fedora. FWIW, I'm using a F25 cloud image.

The offending line appears to be: https://github.com/kubevirt/run/blob/master/demo.sh#L14

Here's the response codes I'm getting with the current redirection:

```
[root@kubevirt fedora]# dnf list installed make >&- 2>&-
[root@kubevirt fedora]# echo $?
1
```

If I remove the redirection...

```
[root@kubevirt fedora]# dnf list installed make 
Last metadata expiration check: 0:53:25 ago on Tue Jul 11 17:00:19 2017.
Installed Packages
make.x86_64                                                                                                       1:4.1-6.fc25                                                                                                       @updates
[root@kubevirt fedora]# echo $?
0
```

And here's if I redirect to `/dev/null`:

```
[root@kubevirt fedora]# dnf list installed make &> /dev/null
[root@kubevirt fedora]# echo $?
0
[root@kubevirt fedora]# nano look.sh 
[root@kubevirt fedora]# dnf list installed intentionally_missing_pack &> /dev/null
[root@kubevirt fedora]# echo $?
1
```

I'll submit a PR here in a moment.

**Comment by fabiand** [comment]
Awesome, thanks for reporting - and fixing.

**Comment by fabiand** [comment]
Thanks for filing and fixing this.

It's now fixed by the new minikube basd demo.
